export interface City {
  id: number;
  x: number;
  y: number;
  name: string;
}

export interface PathStep {
  from: City;
  to: City;
  distance: number;
}

export interface LookaheadResult {
  nextCity: City;
  secondCity?: City; // For 2-step lookahead
  stepCost: number;
  greedyRestCost: number;
  totalCost: number;
  greedyPath: City[]; // The path generated by the greedy rollout
}

export enum LookaheadMode {
  None = 'NONE',
  OneStep = 'ONE_STEP',
  TwoStep = 'TWO_STEP',
}
